-- AlterTable
CREATE SEQUENCE IF NOT EXISTS request_id_seq START 1;
ALTER TABLE "Requests" ALTER COLUMN "requestId" SET DEFAULT (TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD') || '-' || LPAD(NEXTVAL('request_id_seq')::TEXT, 3, '0'))::TEXT;
